package com.rslsolution.speakmateai.dto.assistant;

import java.util.List;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request body for {@code POST /api/assistant/message}.
 * The backend is stateless: conversation history lives in the frontend React state
 * and is sent back on every call (bounded to the last few turns here).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AssistantRequest {

	@NotBlank(message = "Message is required")
	@Size(max = 2000, message = "Message must not exceed 2000 characters")
	private String message;

	/** Opaque id generated by the frontend; echoed back as-is, never persisted. */
	@Size(max = 128, message = "Session ID must not exceed 128 characters")
	private String sessionId;

	/** Current route in the frontend, used to improve navigation suggestions. */
	@Size(max = 256, message = "Current route must not exceed 256 characters")
	private String currentRoute;

	/** Optional recent turns kept in frontend state (role: user | assistant). */
	@Size(max = 30, message = "History must not exceed 30 turns")
	private List<@Valid MessageTurn> history;

	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	public static class MessageTurn {
		@Size(max = 32, message = "Role must not exceed 32 characters")
		private String role;

		@Size(max = 2000, message = "Turn content must not exceed 2000 characters")
		private String content;
	}
}
